/** Backend OAuth error codes — aligned with web `apiError.ts`. */
export const GOOGLE_ACCOUNT_NOT_REGISTERED = "GOOGLE_ACCOUNT_NOT_REGISTERED" as const;
export const GOOGLE_TOKEN_VERIFICATION_FAILED = "GOOGLE_TOKEN_VERIFICATION_FAILED" as const;
export const OAUTH_ACCOUNT_NOT_REGISTERED = "OAUTH_ACCOUNT_NOT_REGISTERED" as const;
export const OAUTH_TOKEN_VERIFICATION_FAILED = "OAUTH_TOKEN_VERIFICATION_FAILED" as const;
/** @deprecated API returns OAUTH_SIGN_IN_FAILED */
export const OAUTH_LINKING_REQUIRED = "OAUTH_LINKING_REQUIRED" as const;
export const OAUTH_EMAIL_REQUIRED = "OAUTH_EMAIL_REQUIRED" as const;
export const OAUTH_SIGN_IN_FAILED = "OAUTH_SIGN_IN_FAILED" as const;
export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED" as const;
