/**
 * CareTip Phase 5 — Apple-level light theme.
 * Brand orange preserved; cooler neutrals, softer semantic colors, WCAG-minded contrast.
 */

export const brand = {
  orange: "#E9781C",
  orangeLight: "#FF9E2D",
  orangeHover: "#FFB04A",
  orangeSoft: "#FFF6ED",
  orangeMuted: "#FFE8D4",
  orangeDeep: "#C45F0F",
} as const;

export const lightColors = {
  background: "#F2F3F5",
  backgroundElevated: "#FAFBFC",
  foreground: "#0B1220",
  card: "#FFFFFF",
  cardElevated: "#FFFFFF",
  cardForeground: "#0B1220",
  cardGlass: "rgba(255,255,255,0.78)",
  primary: brand.orange,
  primaryHover: brand.orangeHover,
  primaryForeground: "#FFFFFF",
  primarySoft: brand.orangeSoft,
  secondary: "#EBEDF0",
  secondaryForeground: "#1A2332",
  muted: "#EBEDF0",
  mutedForeground: "#5B6577",
  accent: brand.orange,
  accentForeground: "#FFFFFF",
  destructive: "#E11D48",
  destructiveForeground: "#FFFFFF",
  destructiveSoft: "#FFF1F2",
  success: "#0D9488",
  successForeground: "#FFFFFF",
  successSoft: "#F0FDFA",
  warning: "#D97706",
  warningForeground: "#FFFFFF",
  warningSoft: "#FFFBEB",
  info: "#2563EB",
  infoSoft: "#EFF6FF",
  border: "#E4E7EC",
  borderStrong: "#CDD2DB",
  input: "#E4E7EC",
  inputBackground: "#FFFFFF",
  ring: brand.orange,
  sidebar: "#FAFBFC",
  sidebarForeground: "#0B1220",
  sidebarBorder: "#E4E7EC",
  overlay: "rgba(11, 18, 32, 0.42)",
  heroGradientStart: "#FFF8F1",
  heroGradientEnd: "#F2F3F5",
  tabBar: "rgba(255,255,255,0.92)",
  tabBarBorder: "rgba(11, 18, 32, 0.06)",
  separator: "rgba(11, 18, 32, 0.06)",
  skeleton: "#E8EAEE",
  skeletonHighlight: "#F7F8FA",
} as const;

/** Prepared for future dark mode — not enabled. */
export const darkColors = {
  background: "#0B0D10",
  backgroundElevated: "#14171C",
  foreground: "#F8FAFC",
  card: "#171A1F",
  cardElevated: "#1C2128",
  cardForeground: "#F8FAFC",
  cardGlass: "rgba(23,26,31,0.88)",
  primary: brand.orange,
  primaryHover: brand.orangeLight,
  primaryForeground: "#FFFFFF",
  primarySoft: "#2A1A0E",
  secondary: "#27272A",
  secondaryForeground: "#FAFAFA",
  muted: "#27272A",
  mutedForeground: "#A1A1AA",
  accent: brand.orange,
  accentForeground: "#FFFFFF",
  destructive: "#FB7185",
  destructiveForeground: "#FFFFFF",
  destructiveSoft: "#3F1515",
  success: "#2DD4BF",
  successForeground: "#042F2E",
  successSoft: "#0F2E22",
  warning: "#F59E0B",
  warningForeground: "#18181B",
  warningSoft: "#3B2A0A",
  info: "#60A5FA",
  infoSoft: "#0F1C33",
  border: "#2A2F38",
  borderStrong: "#3F4654",
  input: "#2A2F38",
  inputBackground: "#14171C",
  ring: brand.orange,
  sidebar: "#11141A",
  sidebarForeground: "#FAFAFA",
  sidebarBorder: "#2A2F38",
  overlay: "rgba(0, 0, 0, 0.55)",
  heroGradientStart: "#1A120C",
  heroGradientEnd: "#0B0D10",
  tabBar: "rgba(23,26,31,0.94)",
  tabBarBorder: "rgba(255,255,255,0.08)",
  separator: "rgba(255,255,255,0.08)",
  skeleton: "#27272A",
  skeletonHighlight: "#3F4654",
} as const;

export type ColorPalette = typeof lightColors;

export const colors: ColorPalette = lightColors;
