/**
 * CareTip fintech light theme — neutral surfaces, orange accent only for emphasis.
 * Palette: Grey / Raenest / Revolut inspired hospitality fintech.
 */

export const brand = {
  orange: "#EB992C",
  orangeLight: "#F0A845",
  orangeHover: "#F5B85A",
  /** Subtle tint for icon wells and active states — never full card fills. */
  orangeSoft: "rgba(235, 153, 44, 0.10)",
  orangeMuted: "rgba(235, 153, 44, 0.18)",
  orangeDeep: "#C47A12",
} as const;

export const lightColors = {
  background: "#F7F8FA",
  backgroundElevated: "#FFFFFF",
  foreground: "#111827",
  card: "#FFFFFF",
  cardElevated: "#FFFFFF",
  cardForeground: "#111827",
  cardGlass: "rgba(255, 255, 255, 0.92)",
  primary: brand.orange,
  primaryHover: brand.orangeHover,
  primaryForeground: "#FFFFFF",
  primarySoft: brand.orangeSoft,
  secondary: "#F3F4F6",
  secondaryForeground: "#111827",
  muted: "#F3F4F6",
  mutedForeground: "#6B7280",
  accent: brand.orange,
  accentForeground: "#FFFFFF",
  destructive: "#DC2626",
  destructiveForeground: "#FFFFFF",
  destructiveSoft: "#FEF2F2",
  success: "#059669",
  successForeground: "#FFFFFF",
  successSoft: "#ECFDF5",
  warning: "#D97706",
  warningForeground: "#FFFFFF",
  warningSoft: "#FFFBEB",
  info: "#2563EB",
  infoSoft: "#EFF6FF",
  border: "#ECEEF2",
  borderStrong: "#D1D5DB",
  input: "#ECEEF2",
  inputBackground: "#FFFFFF",
  ring: brand.orange,
  sidebar: "#FFFFFF",
  sidebarForeground: "#111827",
  sidebarBorder: "#ECEEF2",
  overlay: "rgba(17, 24, 39, 0.45)",
  heroGradientStart: "#FFFFFF",
  heroGradientEnd: "#F7F8FA",
  tabBar: "#FFFFFF",
  tabBarBorder: "#ECEEF2",
  separator: "#ECEEF2",
  skeleton: "#ECEEF2",
  skeletonHighlight: "#F7F8FA",
  /** Neutral chart bars — accent bar uses primary. */
  chartNeutral: "#D1D5DB",
  chartNeutralMuted: "#E5E7EB",
} as const;

/** Dark palette — active via ThemeBridge + useTheme(). */
export const darkColors = {
  background: "#0B0D10",
  backgroundElevated: "#14171C",
  foreground: "#F8FAFC",
  card: "#171A1F",
  cardElevated: "#1C2128",
  cardForeground: "#F8FAFC",
  cardGlass: "rgba(23, 26, 31, 0.88)",
  primary: brand.orange,
  primaryHover: brand.orangeLight,
  primaryForeground: "#FFFFFF",
  primarySoft: "#2A1A0E",
  secondary: "#27272A",
  secondaryForeground: "#FAFAFA",
  muted: "#27272A",
  mutedForeground: "#A1A1AA",
  accent: brand.orange,
  accentForeground: "#FFFFFF",
  destructive: "#FB7185",
  destructiveForeground: "#FFFFFF",
  destructiveSoft: "#3F1515",
  success: "#2DD4BF",
  successForeground: "#042F2E",
  successSoft: "#0F2E22",
  warning: "#F59E0B",
  warningForeground: "#18181B",
  warningSoft: "#3B2A0A",
  info: "#60A5FA",
  infoSoft: "#0F1C33",
  border: "#2A2F38",
  borderStrong: "#3F4654",
  input: "#2A2F38",
  inputBackground: "#14171C",
  ring: brand.orange,
  sidebar: "#11141A",
  sidebarForeground: "#FAFAFA",
  sidebarBorder: "#2A2F38",
  overlay: "rgba(0, 0, 0, 0.55)",
  heroGradientStart: "#1A120C",
  heroGradientEnd: "#0B0D10",
  tabBar: "rgba(23, 26, 31, 0.94)",
  tabBarBorder: "rgba(255, 255, 255, 0.08)",
  separator: "rgba(255, 255, 255, 0.08)",
  skeleton: "#27272A",
  skeletonHighlight: "#3F4654",
  chartNeutral: "#4B5563",
  chartNeutralMuted: "#374151",
} as const;

export type ColorPalette = typeof lightColors | typeof darkColors;

export const colors: ColorPalette = lightColors;
